use mavenmovies;

# 1 - Retrieve the total number of rentals made in the Sakila database.
SELECT COUNT(*) AS total_rentals
FROM rental;

# 2 - Find the average rental duration (in days) of movies rented from the Sakila database.
SELECT AVG(rental_duration) AS average_rental_duration
FROM film;

# 3 - Display the first name and last name of customers in uppercase
SELECT UPPER(first_name) AS first_name_upper,
       UPPER(last_name) AS last_name_upper
FROM customer;

# 4 - Extract the month from the rental date and display it alongside the rental ID.
SELECT rental_id,
MONTH(rental_date) AS rental_month
FROM rental;

# 5 - Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
SELECT customer_id, 
COUNT(*) AS rental_count
FROM rental
GROUP BY customer_id;

# 6 - Find the total revenue generated by each store.
SELECT c.store_id,
SUM(p.amount) AS total_revenue
FROM payment p
JOIN customer c ON p.customer_id = c.customer_id
GROUP BY c.store_id;


# 7 - Determine the total number of rentals for each category of movies.
SELECT c.name AS category,
COUNT(r.rental_id) AS total_rentals
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY c.name
ORDER BY total_rentals DESC;

# 8 - Find the average rental rate of movies in each language.
SELECT l.name AS language,
AVG(f.rental_rate) AS average_rental_rate
FROM film f
JOIN language l ON f.language_id = l.language_id
GROUP BY l.name
ORDER BY average_rental_rate DESC;

# 9 - Display the title of the movie, customer s first name, and last name who rented it.

SELECT f.title AS movie_title, c.first_name, c.last_name
FROM rental r
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film f ON i.film_id = f.film_id
JOIN customer c ON r.customer_id = c.customer_id;

# 10 - Retrieve the names of all actors who have appeared in the film "Gone with the Wind."
SELECT a.first_name, a.last_name
FROM actor a
JOIN film_actor fa ON a.actor_id = fa.actor_id
JOIN film f ON fa.film_id = f.film_id
WHERE f.title = 'Gone with the Wind';

# 11 - Display the top 5 rented movies along with the number of times they've been rented.
SELECT f.title,
COUNT(r.rental_id) AS rental_count
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY rental_count DESC
LIMIT 5;

# 12 - Determine the customers who have rented movies from both stores (store ID 1 and store ID 2).
SELECT r.customer_id
FROM rental r
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN customer c ON r.customer_id = c.customer_id
WHERE i.store_id IN (1, 2)
GROUP BY r.customer_id
HAVING COUNT(DISTINCT i.store_id) = 2;




